// Code generated by MockGen. DO NOT EDIT.
// Source: downtrack.go
//
// Generated by this command:
//
//	mockgen -source downtrack.go -destination mock/downtrack.go
//

// Package mock_sfu is a generated GoMock package.
package mock_sfu

import (
	reflect "reflect"

	buffer "github.com/HMasataka/choice/pkg/buffer"
	sfu "github.com/HMasataka/choice/pkg/sfu"
	rtcp "github.com/pion/rtcp"
	v4 "github.com/pion/webrtc/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockDownTrack is a mock of DownTrack interface.
type MockDownTrack struct {
	ctrl     *gomock.Controller
	recorder *MockDownTrackMockRecorder
	isgomock struct{}
}

// MockDownTrackMockRecorder is the mock recorder for MockDownTrack.
type MockDownTrackMockRecorder struct {
	mock *MockDownTrack
}

// NewMockDownTrack creates a new mock instance.
func NewMockDownTrack(ctrl *gomock.Controller) *MockDownTrack {
	mock := &MockDownTrack{ctrl: ctrl}
	mock.recorder = &MockDownTrackMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDownTrack) EXPECT() *MockDownTrackMockRecorder {
	return m.recorder
}

// Bind mocks base method.
func (m *MockDownTrack) Bind(t v4.TrackLocalContext) (v4.RTPCodecParameters, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bind", t)
	ret0, _ := ret[0].(v4.RTPCodecParameters)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Bind indicates an expected call of Bind.
func (mr *MockDownTrackMockRecorder) Bind(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bind", reflect.TypeOf((*MockDownTrack)(nil).Bind), t)
}

// Bound mocks base method.
func (m *MockDownTrack) Bound() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bound")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Bound indicates an expected call of Bound.
func (mr *MockDownTrackMockRecorder) Bound() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bound", reflect.TypeOf((*MockDownTrack)(nil).Bound))
}

// Close mocks base method.
func (m *MockDownTrack) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockDownTrackMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDownTrack)(nil).Close))
}

// Codec mocks base method.
func (m *MockDownTrack) Codec() v4.RTPCodecCapability {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Codec")
	ret0, _ := ret[0].(v4.RTPCodecCapability)
	return ret0
}

// Codec indicates an expected call of Codec.
func (mr *MockDownTrackMockRecorder) Codec() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Codec", reflect.TypeOf((*MockDownTrack)(nil).Codec))
}

// CreateSenderReport mocks base method.
func (m *MockDownTrack) CreateSenderReport() *rtcp.SenderReport {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSenderReport")
	ret0, _ := ret[0].(*rtcp.SenderReport)
	return ret0
}

// CreateSenderReport indicates an expected call of CreateSenderReport.
func (mr *MockDownTrackMockRecorder) CreateSenderReport() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSenderReport", reflect.TypeOf((*MockDownTrack)(nil).CreateSenderReport))
}

// CreateSourceDescriptionChunks mocks base method.
func (m *MockDownTrack) CreateSourceDescriptionChunks() []rtcp.SourceDescriptionChunk {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSourceDescriptionChunks")
	ret0, _ := ret[0].([]rtcp.SourceDescriptionChunk)
	return ret0
}

// CreateSourceDescriptionChunks indicates an expected call of CreateSourceDescriptionChunks.
func (mr *MockDownTrackMockRecorder) CreateSourceDescriptionChunks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSourceDescriptionChunks", reflect.TypeOf((*MockDownTrack)(nil).CreateSourceDescriptionChunks))
}

// CurrentSpatialLayer mocks base method.
func (m *MockDownTrack) CurrentSpatialLayer() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentSpatialLayer")
	ret0, _ := ret[0].(int)
	return ret0
}

// CurrentSpatialLayer indicates an expected call of CurrentSpatialLayer.
func (mr *MockDownTrackMockRecorder) CurrentSpatialLayer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentSpatialLayer", reflect.TypeOf((*MockDownTrack)(nil).CurrentSpatialLayer))
}

// Enabled mocks base method.
func (m *MockDownTrack) Enabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Enabled indicates an expected call of Enabled.
func (mr *MockDownTrackMockRecorder) Enabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enabled", reflect.TypeOf((*MockDownTrack)(nil).Enabled))
}

// GetMime mocks base method.
func (m *MockDownTrack) GetMime() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMime")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetMime indicates an expected call of GetMime.
func (mr *MockDownTrackMockRecorder) GetMime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMime", reflect.TypeOf((*MockDownTrack)(nil).GetMime))
}

// GetPayloadType mocks base method.
func (m *MockDownTrack) GetPayloadType() uint8 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayloadType")
	ret0, _ := ret[0].(uint8)
	return ret0
}

// GetPayloadType indicates an expected call of GetPayloadType.
func (mr *MockDownTrackMockRecorder) GetPayloadType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayloadType", reflect.TypeOf((*MockDownTrack)(nil).GetPayloadType))
}

// GetSSRC mocks base method.
func (m *MockDownTrack) GetSSRC() uint32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSSRC")
	ret0, _ := ret[0].(uint32)
	return ret0
}

// GetSSRC indicates an expected call of GetSSRC.
func (mr *MockDownTrackMockRecorder) GetSSRC() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSSRC", reflect.TypeOf((*MockDownTrack)(nil).GetSSRC))
}

// GetSimulcast mocks base method.
func (m *MockDownTrack) GetSimulcast() simulcastTrackHelpers {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSimulcast")
	ret0, _ := ret[0].(simulcastTrackHelpers)
	return ret0
}

// GetSimulcast indicates an expected call of GetSimulcast.
func (mr *MockDownTrackMockRecorder) GetSimulcast() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSimulcast", reflect.TypeOf((*MockDownTrack)(nil).GetSimulcast))
}

// GetWriteStream mocks base method.
func (m *MockDownTrack) GetWriteStream() v4.TrackLocalWriter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWriteStream")
	ret0, _ := ret[0].(v4.TrackLocalWriter)
	return ret0
}

// GetWriteStream indicates an expected call of GetWriteStream.
func (mr *MockDownTrackMockRecorder) GetWriteStream() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWriteStream", reflect.TypeOf((*MockDownTrack)(nil).GetWriteStream))
}

// ID mocks base method.
func (m *MockDownTrack) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockDownTrackMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockDownTrack)(nil).ID))
}

// Kind mocks base method.
func (m *MockDownTrack) Kind() v4.RTPCodecType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Kind")
	ret0, _ := ret[0].(v4.RTPCodecType)
	return ret0
}

// Kind indicates an expected call of Kind.
func (mr *MockDownTrackMockRecorder) Kind() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Kind", reflect.TypeOf((*MockDownTrack)(nil).Kind))
}

// Mute mocks base method.
func (m *MockDownTrack) Mute(val bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Mute", val)
}

// Mute indicates an expected call of Mute.
func (mr *MockDownTrackMockRecorder) Mute(val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mute", reflect.TypeOf((*MockDownTrack)(nil).Mute), val)
}

// OnBind mocks base method.
func (m *MockDownTrack) OnBind(fn func()) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnBind", fn)
}

// OnBind indicates an expected call of OnBind.
func (mr *MockDownTrackMockRecorder) OnBind(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnBind", reflect.TypeOf((*MockDownTrack)(nil).OnBind), fn)
}

// OnCloseHandler mocks base method.
func (m *MockDownTrack) OnCloseHandler(fn func()) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnCloseHandler", fn)
}

// OnCloseHandler indicates an expected call of OnCloseHandler.
func (mr *MockDownTrackMockRecorder) OnCloseHandler(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnCloseHandler", reflect.TypeOf((*MockDownTrack)(nil).OnCloseHandler), fn)
}

// RID mocks base method.
func (m *MockDownTrack) RID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RID")
	ret0, _ := ret[0].(string)
	return ret0
}

// RID indicates an expected call of RID.
func (mr *MockDownTrackMockRecorder) RID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RID", reflect.TypeOf((*MockDownTrack)(nil).RID))
}

// SetInitialLayers mocks base method.
func (m *MockDownTrack) SetInitialLayers(spatialLayer, temporalLayer int32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetInitialLayers", spatialLayer, temporalLayer)
}

// SetInitialLayers indicates an expected call of SetInitialLayers.
func (mr *MockDownTrackMockRecorder) SetInitialLayers(spatialLayer, temporalLayer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInitialLayers", reflect.TypeOf((*MockDownTrack)(nil).SetInitialLayers), spatialLayer, temporalLayer)
}

// SetLastSSRC mocks base method.
func (m *MockDownTrack) SetLastSSRC(ssrc uint32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLastSSRC", ssrc)
}

// SetLastSSRC indicates an expected call of SetLastSSRC.
func (mr *MockDownTrackMockRecorder) SetLastSSRC(ssrc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLastSSRC", reflect.TypeOf((*MockDownTrack)(nil).SetLastSSRC), ssrc)
}

// SetMaxSpatialLayer mocks base method.
func (m *MockDownTrack) SetMaxSpatialLayer(layer int32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMaxSpatialLayer", layer)
}

// SetMaxSpatialLayer indicates an expected call of SetMaxSpatialLayer.
func (mr *MockDownTrackMockRecorder) SetMaxSpatialLayer(layer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMaxSpatialLayer", reflect.TypeOf((*MockDownTrack)(nil).SetMaxSpatialLayer), layer)
}

// SetMaxTemporalLayer mocks base method.
func (m *MockDownTrack) SetMaxTemporalLayer(layer int32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMaxTemporalLayer", layer)
}

// SetMaxTemporalLayer indicates an expected call of SetMaxTemporalLayer.
func (mr *MockDownTrackMockRecorder) SetMaxTemporalLayer(layer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMaxTemporalLayer", reflect.TypeOf((*MockDownTrack)(nil).SetMaxTemporalLayer), layer)
}

// SetPayload mocks base method.
func (m *MockDownTrack) SetPayload(payload *[]byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPayload", payload)
}

// SetPayload indicates an expected call of SetPayload.
func (mr *MockDownTrackMockRecorder) SetPayload(payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPayload", reflect.TypeOf((*MockDownTrack)(nil).SetPayload), payload)
}

// SetTrackType mocks base method.
func (m *MockDownTrack) SetTrackType(trackType sfu.DownTrackType) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrackType", trackType)
}

// SetTrackType indicates an expected call of SetTrackType.
func (mr *MockDownTrackMockRecorder) SetTrackType(trackType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrackType", reflect.TypeOf((*MockDownTrack)(nil).SetTrackType), trackType)
}

// SetTransceiver mocks base method.
func (m *MockDownTrack) SetTransceiver(transceiver *v4.RTPTransceiver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTransceiver", transceiver)
}

// SetTransceiver indicates an expected call of SetTransceiver.
func (mr *MockDownTrackMockRecorder) SetTransceiver(transceiver any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTransceiver", reflect.TypeOf((*MockDownTrack)(nil).SetTransceiver), transceiver)
}

// Stop mocks base method.
func (m *MockDownTrack) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockDownTrackMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockDownTrack)(nil).Stop))
}

// StreamID mocks base method.
func (m *MockDownTrack) StreamID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamID")
	ret0, _ := ret[0].(string)
	return ret0
}

// StreamID indicates an expected call of StreamID.
func (mr *MockDownTrackMockRecorder) StreamID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamID", reflect.TypeOf((*MockDownTrack)(nil).StreamID))
}

// SwitchSpatialLayer mocks base method.
func (m *MockDownTrack) SwitchSpatialLayer(targetLayer int32, setAsMax bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SwitchSpatialLayer", targetLayer, setAsMax)
	ret0, _ := ret[0].(error)
	return ret0
}

// SwitchSpatialLayer indicates an expected call of SwitchSpatialLayer.
func (mr *MockDownTrackMockRecorder) SwitchSpatialLayer(targetLayer, setAsMax any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchSpatialLayer", reflect.TypeOf((*MockDownTrack)(nil).SwitchSpatialLayer), targetLayer, setAsMax)
}

// SwitchSpatialLayerDone mocks base method.
func (m *MockDownTrack) SwitchSpatialLayerDone(layer int32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SwitchSpatialLayerDone", layer)
}

// SwitchSpatialLayerDone indicates an expected call of SwitchSpatialLayerDone.
func (mr *MockDownTrackMockRecorder) SwitchSpatialLayerDone(layer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchSpatialLayerDone", reflect.TypeOf((*MockDownTrack)(nil).SwitchSpatialLayerDone), layer)
}

// SwitchTemporalLayer mocks base method.
func (m *MockDownTrack) SwitchTemporalLayer(targetLayer int32, setAsMax bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SwitchTemporalLayer", targetLayer, setAsMax)
}

// SwitchTemporalLayer indicates an expected call of SwitchTemporalLayer.
func (mr *MockDownTrackMockRecorder) SwitchTemporalLayer(targetLayer, setAsMax any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchTemporalLayer", reflect.TypeOf((*MockDownTrack)(nil).SwitchTemporalLayer), targetLayer, setAsMax)
}

// Unbind mocks base method.
func (m *MockDownTrack) Unbind(arg0 v4.TrackLocalContext) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unbind", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unbind indicates an expected call of Unbind.
func (mr *MockDownTrackMockRecorder) Unbind(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unbind", reflect.TypeOf((*MockDownTrack)(nil).Unbind), arg0)
}

// UpdateStats mocks base method.
func (m *MockDownTrack) UpdateStats(packetLen uint32) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateStats", packetLen)
}

// UpdateStats indicates an expected call of UpdateStats.
func (mr *MockDownTrackMockRecorder) UpdateStats(packetLen any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStats", reflect.TypeOf((*MockDownTrack)(nil).UpdateStats), packetLen)
}

// UptrackLayersChange mocks base method.
func (m *MockDownTrack) UptrackLayersChange(availableLayers []uint16) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UptrackLayersChange", availableLayers)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UptrackLayersChange indicates an expected call of UptrackLayersChange.
func (mr *MockDownTrackMockRecorder) UptrackLayersChange(availableLayers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UptrackLayersChange", reflect.TypeOf((*MockDownTrack)(nil).UptrackLayersChange), availableLayers)
}

// WriteRTP mocks base method.
func (m *MockDownTrack) WriteRTP(p *buffer.ExtPacket, layer int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteRTP", p, layer)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteRTP indicates an expected call of WriteRTP.
func (mr *MockDownTrackMockRecorder) WriteRTP(p, layer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteRTP", reflect.TypeOf((*MockDownTrack)(nil).WriteRTP), p, layer)
}
