// Code generated by MockGen. DO NOT EDIT.
// Source: datachannel.go
//
// Generated by this command:
//
//	mockgen -source datachannel.go -destination mock/message_processor.go
//

// Package mock_sfu is a generated GoMock package.
package mock_sfu

import (
	context "context"
	reflect "reflect"

	sfu "github.com/HMasataka/choice/pkg/sfu"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageProcessor is a mock of MessageProcessor interface.
type MockMessageProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockMessageProcessorMockRecorder
	isgomock struct{}
}

// MockMessageProcessorMockRecorder is the mock recorder for MockMessageProcessor.
type MockMessageProcessorMockRecorder struct {
	mock *MockMessageProcessor
}

// NewMockMessageProcessor creates a new mock instance.
func NewMockMessageProcessor(ctrl *gomock.Controller) *MockMessageProcessor {
	mock := &MockMessageProcessor{ctrl: ctrl}
	mock.recorder = &MockMessageProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageProcessor) EXPECT() *MockMessageProcessorMockRecorder {
	return m.recorder
}

// Process mocks base method.
func (m *MockMessageProcessor) Process(ctx context.Context, args sfu.ProcessArgs) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Process", ctx, args)
}

// Process indicates an expected call of Process.
func (mr *MockMessageProcessorMockRecorder) Process(ctx, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockMessageProcessor)(nil).Process), ctx, args)
}
