// Code generated by MockGen. DO NOT EDIT.
// Source: peer.go
//
// Generated by this command:
//
//	mockgen -source peer.go -destination mock/peer.go
//

// Package mock_sfu is a generated GoMock package.
package mock_sfu

import (
	context "context"
	reflect "reflect"

	sfu "github.com/HMasataka/choice/pkg/sfu"
	webrtc "github.com/pion/webrtc/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockPeer is a mock of Peer interface.
type MockPeer struct {
	ctrl     *gomock.Controller
	recorder *MockPeerMockRecorder
	isgomock struct{}
}

// MockPeerMockRecorder is the mock recorder for MockPeer.
type MockPeerMockRecorder struct {
	mock *MockPeer
}

// NewMockPeer creates a new mock instance.
func NewMockPeer(ctrl *gomock.Controller) *MockPeer {
	mock := &MockPeer{ctrl: ctrl}
	mock.recorder = &MockPeerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPeer) EXPECT() *MockPeerMockRecorder {
	return m.recorder
}

// Join mocks base method.
func (m *MockPeer) Join(ctx context.Context, sessionID, userID string, config sfu.JoinConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Join", ctx, sessionID, userID, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// Join indicates an expected call of Join.
func (mr *MockPeerMockRecorder) Join(ctx, sessionID, userID, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Join", reflect.TypeOf((*MockPeer)(nil).Join), ctx, sessionID, userID, config)
}

// Publisher mocks base method.
func (m *MockPeer) Publisher() sfu.Publisher {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publisher")
	ret0, _ := ret[0].(sfu.Publisher)
	return ret0
}

// Publisher indicates an expected call of Publisher.
func (mr *MockPeerMockRecorder) Publisher() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publisher", reflect.TypeOf((*MockPeer)(nil).Publisher))
}

// SetOnIceCandidate mocks base method.
func (m *MockPeer) SetOnIceCandidate(f func(*webrtc.ICECandidateInit, sfu.ConnectionType)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOnIceCandidate", f)
}

// SetOnIceCandidate indicates an expected call of SetOnIceCandidate.
func (mr *MockPeerMockRecorder) SetOnIceCandidate(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOnIceCandidate", reflect.TypeOf((*MockPeer)(nil).SetOnIceCandidate), f)
}

// SetOnIceConnectionStateChange mocks base method.
func (m *MockPeer) SetOnIceConnectionStateChange(f func(webrtc.ICEConnectionState)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOnIceConnectionStateChange", f)
}

// SetOnIceConnectionStateChange indicates an expected call of SetOnIceConnectionStateChange.
func (mr *MockPeerMockRecorder) SetOnIceConnectionStateChange(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOnIceConnectionStateChange", reflect.TypeOf((*MockPeer)(nil).SetOnIceConnectionStateChange), f)
}

// SetOnOffer mocks base method.
func (m *MockPeer) SetOnOffer(f func(*webrtc.SessionDescription)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOnOffer", f)
}

// SetOnOffer indicates an expected call of SetOnOffer.
func (mr *MockPeerMockRecorder) SetOnOffer(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOnOffer", reflect.TypeOf((*MockPeer)(nil).SetOnOffer), f)
}

// SetRemoteDescription mocks base method.
func (m *MockPeer) SetRemoteDescription(sdp webrtc.SessionDescription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRemoteDescription", sdp)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRemoteDescription indicates an expected call of SetRemoteDescription.
func (mr *MockPeerMockRecorder) SetRemoteDescription(sdp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRemoteDescription", reflect.TypeOf((*MockPeer)(nil).SetRemoteDescription), sdp)
}

// Subscriber mocks base method.
func (m *MockPeer) Subscriber() sfu.Subscriber {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscriber")
	ret0, _ := ret[0].(sfu.Subscriber)
	return ret0
}

// Subscriber indicates an expected call of Subscriber.
func (mr *MockPeerMockRecorder) Subscriber() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscriber", reflect.TypeOf((*MockPeer)(nil).Subscriber))
}

// Trickle mocks base method.
func (m *MockPeer) Trickle(candidate webrtc.ICECandidateInit, target sfu.ConnectionType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trickle", candidate, target)
	ret0, _ := ret[0].(error)
	return ret0
}

// Trickle indicates an expected call of Trickle.
func (mr *MockPeerMockRecorder) Trickle(candidate, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trickle", reflect.TypeOf((*MockPeer)(nil).Trickle), candidate, target)
}

// UserID mocks base method.
func (m *MockPeer) UserID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserID")
	ret0, _ := ret[0].(string)
	return ret0
}

// UserID indicates an expected call of UserID.
func (mr *MockPeerMockRecorder) UserID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserID", reflect.TypeOf((*MockPeer)(nil).UserID))
}
