// Code generated by MockGen. DO NOT EDIT.
// Source: publisher.go
//
// Generated by this command:
//
//	mockgen -source publisher.go -destination mock/publisher.go
//

// Package mock_sfu is a generated GoMock package.
package mock_sfu

import (
	reflect "reflect"

	relay "github.com/HMasataka/choice/pkg/relay"
	sfu "github.com/HMasataka/choice/pkg/sfu"
	webrtc "github.com/pion/webrtc/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
	isgomock struct{}
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// AddICECandidate mocks base method.
func (m *MockPublisher) AddICECandidate(candidate webrtc.ICECandidateInit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddICECandidate", candidate)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddICECandidate indicates an expected call of AddICECandidate.
func (mr *MockPublisherMockRecorder) AddICECandidate(candidate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddICECandidate", reflect.TypeOf((*MockPublisher)(nil).AddICECandidate), candidate)
}

// AddRelayFanOutDataChannel mocks base method.
func (m *MockPublisher) AddRelayFanOutDataChannel(label string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddRelayFanOutDataChannel", label)
}

// AddRelayFanOutDataChannel indicates an expected call of AddRelayFanOutDataChannel.
func (mr *MockPublisherMockRecorder) AddRelayFanOutDataChannel(label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRelayFanOutDataChannel", reflect.TypeOf((*MockPublisher)(nil).AddRelayFanOutDataChannel), label)
}

// Answer mocks base method.
func (m *MockPublisher) Answer(offer webrtc.SessionDescription) (webrtc.SessionDescription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Answer", offer)
	ret0, _ := ret[0].(webrtc.SessionDescription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Answer indicates an expected call of Answer.
func (mr *MockPublisherMockRecorder) Answer(offer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Answer", reflect.TypeOf((*MockPublisher)(nil).Answer), offer)
}

// Close mocks base method.
func (m *MockPublisher) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockPublisherMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPublisher)(nil).Close))
}

// GetRelayedDataChannels mocks base method.
func (m *MockPublisher) GetRelayedDataChannels(label string) []*webrtc.DataChannel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelayedDataChannels", label)
	ret0, _ := ret[0].([]*webrtc.DataChannel)
	return ret0
}

// GetRelayedDataChannels indicates an expected call of GetRelayedDataChannels.
func (mr *MockPublisherMockRecorder) GetRelayedDataChannels(label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelayedDataChannels", reflect.TypeOf((*MockPublisher)(nil).GetRelayedDataChannels), label)
}

// GetRouter mocks base method.
func (m *MockPublisher) GetRouter() sfu.Router {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRouter")
	ret0, _ := ret[0].(sfu.Router)
	return ret0
}

// GetRouter indicates an expected call of GetRouter.
func (mr *MockPublisherMockRecorder) GetRouter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRouter", reflect.TypeOf((*MockPublisher)(nil).GetRouter))
}

// OnICECandidate mocks base method.
func (m *MockPublisher) OnICECandidate(f func(*webrtc.ICECandidate)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnICECandidate", f)
}

// OnICECandidate indicates an expected call of OnICECandidate.
func (mr *MockPublisherMockRecorder) OnICECandidate(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnICECandidate", reflect.TypeOf((*MockPublisher)(nil).OnICECandidate), f)
}

// OnICEConnectionStateChange mocks base method.
func (m *MockPublisher) OnICEConnectionStateChange(f func(webrtc.ICEConnectionState)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnICEConnectionStateChange", f)
}

// OnICEConnectionStateChange indicates an expected call of OnICEConnectionStateChange.
func (mr *MockPublisherMockRecorder) OnICEConnectionStateChange(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnICEConnectionStateChange", reflect.TypeOf((*MockPublisher)(nil).OnICEConnectionStateChange), f)
}

// OnPublisherTrack mocks base method.
func (m *MockPublisher) OnPublisherTrack(f func(sfu.PublisherTrack)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnPublisherTrack", f)
}

// OnPublisherTrack indicates an expected call of OnPublisherTrack.
func (mr *MockPublisherMockRecorder) OnPublisherTrack(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnPublisherTrack", reflect.TypeOf((*MockPublisher)(nil).OnPublisherTrack), f)
}

// PeerConnection mocks base method.
func (m *MockPublisher) PeerConnection() *webrtc.PeerConnection {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PeerConnection")
	ret0, _ := ret[0].(*webrtc.PeerConnection)
	return ret0
}

// PeerConnection indicates an expected call of PeerConnection.
func (mr *MockPublisherMockRecorder) PeerConnection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PeerConnection", reflect.TypeOf((*MockPublisher)(nil).PeerConnection))
}

// PublisherTracks mocks base method.
func (m *MockPublisher) PublisherTracks() []sfu.PublisherTrack {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublisherTracks")
	ret0, _ := ret[0].([]sfu.PublisherTrack)
	return ret0
}

// PublisherTracks indicates an expected call of PublisherTracks.
func (mr *MockPublisherMockRecorder) PublisherTracks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublisherTracks", reflect.TypeOf((*MockPublisher)(nil).PublisherTracks))
}

// Relay mocks base method.
func (m *MockPublisher) Relay(signalFn func(relay.PeerMeta, []byte) ([]byte, error), options ...func(*sfu.PublisherRelay)) (*relay.Peer, error) {
	m.ctrl.T.Helper()
	varargs := []any{signalFn}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Relay", varargs...)
	ret0, _ := ret[0].(*relay.Peer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Relay indicates an expected call of Relay.
func (mr *MockPublisherMockRecorder) Relay(signalFn any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{signalFn}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Relay", reflect.TypeOf((*MockPublisher)(nil).Relay), varargs...)
}

// Relayed mocks base method.
func (m *MockPublisher) Relayed() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Relayed")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Relayed indicates an expected call of Relayed.
func (mr *MockPublisherMockRecorder) Relayed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Relayed", reflect.TypeOf((*MockPublisher)(nil).Relayed))
}

// SignalingState mocks base method.
func (m *MockPublisher) SignalingState() webrtc.SignalingState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignalingState")
	ret0, _ := ret[0].(webrtc.SignalingState)
	return ret0
}

// SignalingState indicates an expected call of SignalingState.
func (mr *MockPublisherMockRecorder) SignalingState() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignalingState", reflect.TypeOf((*MockPublisher)(nil).SignalingState))
}

// Tracks mocks base method.
func (m *MockPublisher) Tracks() []*webrtc.TrackRemote {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tracks")
	ret0, _ := ret[0].([]*webrtc.TrackRemote)
	return ret0
}

// Tracks indicates an expected call of Tracks.
func (mr *MockPublisherMockRecorder) Tracks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tracks", reflect.TypeOf((*MockPublisher)(nil).Tracks))
}
