// Code generated by MockGen. DO NOT EDIT.
// Source: receiver.go
//
// Generated by this command:
//
//	mockgen -source receiver.go -destination mock/receiver.go
//

// Package mock_sfu is a generated GoMock package.
package mock_sfu

import (
	reflect "reflect"

	buffer "github.com/HMasataka/choice/pkg/buffer"
	sfu "github.com/HMasataka/choice/pkg/sfu"
	rtcp "github.com/pion/rtcp"
	webrtc "github.com/pion/webrtc/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockReceiver is a mock of Receiver interface.
type MockReceiver struct {
	ctrl     *gomock.Controller
	recorder *MockReceiverMockRecorder
	isgomock struct{}
}

// MockReceiverMockRecorder is the mock recorder for MockReceiver.
type MockReceiverMockRecorder struct {
	mock *MockReceiver
}

// NewMockReceiver creates a new mock instance.
func NewMockReceiver(ctrl *gomock.Controller) *MockReceiver {
	mock := &MockReceiver{ctrl: ctrl}
	mock.recorder = &MockReceiverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReceiver) EXPECT() *MockReceiverMockRecorder {
	return m.recorder
}

// AddDownTrack mocks base method.
func (m *MockReceiver) AddDownTrack(track sfu.DownTrack, bestQualityFirst bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddDownTrack", track, bestQualityFirst)
}

// AddDownTrack indicates an expected call of AddDownTrack.
func (mr *MockReceiverMockRecorder) AddDownTrack(track, bestQualityFirst any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDownTrack", reflect.TypeOf((*MockReceiver)(nil).AddDownTrack), track, bestQualityFirst)
}

// AddUpTrack mocks base method.
func (m *MockReceiver) AddUpTrack(track *webrtc.TrackRemote, arg1 *buffer.Buffer, bestQualityFirst bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddUpTrack", track, arg1, bestQualityFirst)
}

// AddUpTrack indicates an expected call of AddUpTrack.
func (mr *MockReceiverMockRecorder) AddUpTrack(track, arg1, bestQualityFirst any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUpTrack", reflect.TypeOf((*MockReceiver)(nil).AddUpTrack), track, arg1, bestQualityFirst)
}

// Codec mocks base method.
func (m *MockReceiver) Codec() webrtc.RTPCodecParameters {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Codec")
	ret0, _ := ret[0].(webrtc.RTPCodecParameters)
	return ret0
}

// Codec indicates an expected call of Codec.
func (mr *MockReceiverMockRecorder) Codec() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Codec", reflect.TypeOf((*MockReceiver)(nil).Codec))
}

// DeleteDownTrack mocks base method.
func (m *MockReceiver) DeleteDownTrack(layer int, id string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteDownTrack", layer, id)
}

// DeleteDownTrack indicates an expected call of DeleteDownTrack.
func (mr *MockReceiverMockRecorder) DeleteDownTrack(layer, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDownTrack", reflect.TypeOf((*MockReceiver)(nil).DeleteDownTrack), layer, id)
}

// GetBitrate mocks base method.
func (m *MockReceiver) GetBitrate() [3]uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBitrate")
	ret0, _ := ret[0].([3]uint64)
	return ret0
}

// GetBitrate indicates an expected call of GetBitrate.
func (mr *MockReceiverMockRecorder) GetBitrate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBitrate", reflect.TypeOf((*MockReceiver)(nil).GetBitrate))
}

// GetMaxTemporalLayer mocks base method.
func (m *MockReceiver) GetMaxTemporalLayer() [3]int32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaxTemporalLayer")
	ret0, _ := ret[0].([3]int32)
	return ret0
}

// GetMaxTemporalLayer indicates an expected call of GetMaxTemporalLayer.
func (mr *MockReceiverMockRecorder) GetMaxTemporalLayer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaxTemporalLayer", reflect.TypeOf((*MockReceiver)(nil).GetMaxTemporalLayer))
}

// GetSenderReportTime mocks base method.
func (m *MockReceiver) GetSenderReportTime(layer int) (uint32, uint64) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSenderReportTime", layer)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(uint64)
	return ret0, ret1
}

// GetSenderReportTime indicates an expected call of GetSenderReportTime.
func (mr *MockReceiverMockRecorder) GetSenderReportTime(layer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSenderReportTime", reflect.TypeOf((*MockReceiver)(nil).GetSenderReportTime), layer)
}

// Kind mocks base method.
func (m *MockReceiver) Kind() webrtc.RTPCodecType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Kind")
	ret0, _ := ret[0].(webrtc.RTPCodecType)
	return ret0
}

// Kind indicates an expected call of Kind.
func (mr *MockReceiverMockRecorder) Kind() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Kind", reflect.TypeOf((*MockReceiver)(nil).Kind))
}

// OnCloseHandler mocks base method.
func (m *MockReceiver) OnCloseHandler(fn func()) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnCloseHandler", fn)
}

// OnCloseHandler indicates an expected call of OnCloseHandler.
func (mr *MockReceiverMockRecorder) OnCloseHandler(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnCloseHandler", reflect.TypeOf((*MockReceiver)(nil).OnCloseHandler), fn)
}

// RetransmitPackets mocks base method.
func (m *MockReceiver) RetransmitPackets(track sfu.DownTrack, packets []sfu.PacketMeta) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetransmitPackets", track, packets)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetransmitPackets indicates an expected call of RetransmitPackets.
func (mr *MockReceiverMockRecorder) RetransmitPackets(track, packets any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetransmitPackets", reflect.TypeOf((*MockReceiver)(nil).RetransmitPackets), track, packets)
}

// SSRC mocks base method.
func (m *MockReceiver) SSRC(layer int) uint32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SSRC", layer)
	ret0, _ := ret[0].(uint32)
	return ret0
}

// SSRC indicates an expected call of SSRC.
func (mr *MockReceiverMockRecorder) SSRC(layer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SSRC", reflect.TypeOf((*MockReceiver)(nil).SSRC), layer)
}

// SendRTCP mocks base method.
func (m *MockReceiver) SendRTCP(p []rtcp.Packet) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendRTCP", p)
}

// SendRTCP indicates an expected call of SendRTCP.
func (mr *MockReceiverMockRecorder) SendRTCP(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendRTCP", reflect.TypeOf((*MockReceiver)(nil).SendRTCP), p)
}

// SetRTCPCh mocks base method.
func (m *MockReceiver) SetRTCPCh(ch chan []rtcp.Packet) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRTCPCh", ch)
}

// SetRTCPCh indicates an expected call of SetRTCPCh.
func (mr *MockReceiverMockRecorder) SetRTCPCh(ch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRTCPCh", reflect.TypeOf((*MockReceiver)(nil).SetRTCPCh), ch)
}

// SetTrackMeta mocks base method.
func (m *MockReceiver) SetTrackMeta(trackID, streamID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrackMeta", trackID, streamID)
}

// SetTrackMeta indicates an expected call of SetTrackMeta.
func (mr *MockReceiverMockRecorder) SetTrackMeta(trackID, streamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrackMeta", reflect.TypeOf((*MockReceiver)(nil).SetTrackMeta), trackID, streamID)
}

// StreamID mocks base method.
func (m *MockReceiver) StreamID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamID")
	ret0, _ := ret[0].(string)
	return ret0
}

// StreamID indicates an expected call of StreamID.
func (mr *MockReceiverMockRecorder) StreamID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamID", reflect.TypeOf((*MockReceiver)(nil).StreamID))
}

// SwitchDownTrack mocks base method.
func (m *MockReceiver) SwitchDownTrack(track sfu.DownTrack, layer int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SwitchDownTrack", track, layer)
	ret0, _ := ret[0].(error)
	return ret0
}

// SwitchDownTrack indicates an expected call of SwitchDownTrack.
func (mr *MockReceiverMockRecorder) SwitchDownTrack(track, layer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchDownTrack", reflect.TypeOf((*MockReceiver)(nil).SwitchDownTrack), track, layer)
}

// TrackID mocks base method.
func (m *MockReceiver) TrackID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackID")
	ret0, _ := ret[0].(string)
	return ret0
}

// TrackID indicates an expected call of TrackID.
func (mr *MockReceiverMockRecorder) TrackID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackID", reflect.TypeOf((*MockReceiver)(nil).TrackID))
}
