// Code generated by MockGen. DO NOT EDIT.
// Source: router.go
//
// Generated by this command:
//
//	mockgen -source router.go -destination mock/router.go
//

// Package mock_sfu is a generated GoMock package.
package mock_sfu

import (
	reflect "reflect"

	sfu "github.com/HMasataka/choice/pkg/sfu"
	rtcp "github.com/pion/rtcp"
	webrtc "github.com/pion/webrtc/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockRouter is a mock of Router interface.
type MockRouter struct {
	ctrl     *gomock.Controller
	recorder *MockRouterMockRecorder
	isgomock struct{}
}

// MockRouterMockRecorder is the mock recorder for MockRouter.
type MockRouterMockRecorder struct {
	mock *MockRouter
}

// NewMockRouter creates a new mock instance.
func NewMockRouter(ctrl *gomock.Controller) *MockRouter {
	mock := &MockRouter{ctrl: ctrl}
	mock.recorder = &MockRouterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouter) EXPECT() *MockRouterMockRecorder {
	return m.recorder
}

// AddDownTrack mocks base method.
func (m *MockRouter) AddDownTrack(s sfu.Subscriber, r sfu.Receiver) (sfu.DownTrack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDownTrack", s, r)
	ret0, _ := ret[0].(sfu.DownTrack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddDownTrack indicates an expected call of AddDownTrack.
func (mr *MockRouterMockRecorder) AddDownTrack(s, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDownTrack", reflect.TypeOf((*MockRouter)(nil).AddDownTrack), s, r)
}

// AddDownTracks mocks base method.
func (m *MockRouter) AddDownTracks(s sfu.Subscriber, r sfu.Receiver) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDownTracks", s, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDownTracks indicates an expected call of AddDownTracks.
func (mr *MockRouterMockRecorder) AddDownTracks(s, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDownTracks", reflect.TypeOf((*MockRouter)(nil).AddDownTracks), s, r)
}

// AddReceiver mocks base method.
func (m *MockRouter) AddReceiver(receiver *webrtc.RTPReceiver, track *webrtc.TrackRemote, trackID, streamID string) (sfu.Receiver, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddReceiver", receiver, track, trackID, streamID)
	ret0, _ := ret[0].(sfu.Receiver)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// AddReceiver indicates an expected call of AddReceiver.
func (mr *MockRouterMockRecorder) AddReceiver(receiver, track, trackID, streamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddReceiver", reflect.TypeOf((*MockRouter)(nil).AddReceiver), receiver, track, trackID, streamID)
}

// GetReceiver mocks base method.
func (m *MockRouter) GetReceiver() map[string]sfu.Receiver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReceiver")
	ret0, _ := ret[0].(map[string]sfu.Receiver)
	return ret0
}

// GetReceiver indicates an expected call of GetReceiver.
func (mr *MockRouterMockRecorder) GetReceiver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReceiver", reflect.TypeOf((*MockRouter)(nil).GetReceiver))
}

// OnAddReceiverTrack mocks base method.
func (m *MockRouter) OnAddReceiverTrack(f func(sfu.Receiver)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnAddReceiverTrack", f)
}

// OnAddReceiverTrack indicates an expected call of OnAddReceiverTrack.
func (mr *MockRouterMockRecorder) OnAddReceiverTrack(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnAddReceiverTrack", reflect.TypeOf((*MockRouter)(nil).OnAddReceiverTrack), f)
}

// OnDelReceiverTrack mocks base method.
func (m *MockRouter) OnDelReceiverTrack(f func(sfu.Receiver)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnDelReceiverTrack", f)
}

// OnDelReceiverTrack indicates an expected call of OnDelReceiverTrack.
func (mr *MockRouterMockRecorder) OnDelReceiverTrack(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnDelReceiverTrack", reflect.TypeOf((*MockRouter)(nil).OnDelReceiverTrack), f)
}

// SetRTCPWriter mocks base method.
func (m *MockRouter) SetRTCPWriter(arg0 func([]rtcp.Packet) error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRTCPWriter", arg0)
}

// SetRTCPWriter indicates an expected call of SetRTCPWriter.
func (mr *MockRouterMockRecorder) SetRTCPWriter(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRTCPWriter", reflect.TypeOf((*MockRouter)(nil).SetRTCPWriter), arg0)
}

// Stop mocks base method.
func (m *MockRouter) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockRouterMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockRouter)(nil).Stop))
}

// UserID mocks base method.
func (m *MockRouter) UserID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserID")
	ret0, _ := ret[0].(string)
	return ret0
}

// UserID indicates an expected call of UserID.
func (mr *MockRouterMockRecorder) UserID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserID", reflect.TypeOf((*MockRouter)(nil).UserID))
}
