// Code generated by MockGen. DO NOT EDIT.
// Source: sfu.go
//
// Generated by this command:
//
//	mockgen -source sfu.go -destination mock/session_provider.go
//

// Package mock_sfu is a generated GoMock package.
package mock_sfu

import (
	reflect "reflect"

	sfu "github.com/HMasataka/choice/pkg/sfu"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionProvider is a mock of SessionProvider interface.
type MockSessionProvider struct {
	ctrl     *gomock.Controller
	recorder *MockSessionProviderMockRecorder
	isgomock struct{}
}

// MockSessionProviderMockRecorder is the mock recorder for MockSessionProvider.
type MockSessionProviderMockRecorder struct {
	mock *MockSessionProvider
}

// NewMockSessionProvider creates a new mock instance.
func NewMockSessionProvider(ctrl *gomock.Controller) *MockSessionProvider {
	mock := &MockSessionProvider{ctrl: ctrl}
	mock.recorder = &MockSessionProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionProvider) EXPECT() *MockSessionProviderMockRecorder {
	return m.recorder
}

// GetSession mocks base method.
func (m *MockSessionProvider) GetSession(id string) sfu.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", id)
	ret0, _ := ret[0].(sfu.Session)
	return ret0
}

// GetSession indicates an expected call of GetSession.
func (mr *MockSessionProviderMockRecorder) GetSession(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockSessionProvider)(nil).GetSession), id)
}

// GetTransportConfig mocks base method.
func (m *MockSessionProvider) GetTransportConfig() sfu.WebRTCTransportConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransportConfig")
	ret0, _ := ret[0].(sfu.WebRTCTransportConfig)
	return ret0
}

// GetTransportConfig indicates an expected call of GetTransportConfig.
func (mr *MockSessionProviderMockRecorder) GetTransportConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransportConfig", reflect.TypeOf((*MockSessionProvider)(nil).GetTransportConfig))
}
