// Code generated by MockGen. DO NOT EDIT.
// Source: session.go
//
// Generated by this command:
//
//	mockgen -source session.go -destination mock/session.go
//

// Package mock_sfu is a generated GoMock package.
package mock_sfu

import (
	reflect "reflect"

	sfu "github.com/HMasataka/choice/pkg/sfu"
	webrtc "github.com/pion/webrtc/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockSession is a mock of Session interface.
type MockSession struct {
	ctrl     *gomock.Controller
	recorder *MockSessionMockRecorder
	isgomock struct{}
}

// MockSessionMockRecorder is the mock recorder for MockSession.
type MockSessionMockRecorder struct {
	mock *MockSession
}

// NewMockSession creates a new mock instance.
func NewMockSession(ctrl *gomock.Controller) *MockSession {
	mock := &MockSession{ctrl: ctrl}
	mock.recorder = &MockSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSession) EXPECT() *MockSessionMockRecorder {
	return m.recorder
}

// AddDatachannel mocks base method.
func (m *MockSession) AddDatachannel(owner string, dc *webrtc.DataChannel) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddDatachannel", owner, dc)
}

// AddDatachannel indicates an expected call of AddDatachannel.
func (mr *MockSessionMockRecorder) AddDatachannel(owner, dc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDatachannel", reflect.TypeOf((*MockSession)(nil).AddDatachannel), owner, dc)
}

// AddPeer mocks base method.
func (m *MockSession) AddPeer(peer sfu.Peer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddPeer", peer)
}

// AddPeer indicates an expected call of AddPeer.
func (mr *MockSessionMockRecorder) AddPeer(peer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPeer", reflect.TypeOf((*MockSession)(nil).AddPeer), peer)
}

// AddRelayPeer mocks base method.
func (m *MockSession) AddRelayPeer(peerID string, signalData []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRelayPeer", peerID, signalData)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddRelayPeer indicates an expected call of AddRelayPeer.
func (mr *MockSessionMockRecorder) AddRelayPeer(peerID, signalData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRelayPeer", reflect.TypeOf((*MockSession)(nil).AddRelayPeer), peerID, signalData)
}

// AudioObserver mocks base method.
func (m *MockSession) AudioObserver() *sfu.AudioObserver {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AudioObserver")
	ret0, _ := ret[0].(*sfu.AudioObserver)
	return ret0
}

// AudioObserver indicates an expected call of AudioObserver.
func (mr *MockSessionMockRecorder) AudioObserver() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AudioObserver", reflect.TypeOf((*MockSession)(nil).AudioObserver))
}

// FanOutMessage mocks base method.
func (m *MockSession) FanOutMessage(origin, label string, msg webrtc.DataChannelMessage) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FanOutMessage", origin, label, msg)
}

// FanOutMessage indicates an expected call of FanOutMessage.
func (mr *MockSessionMockRecorder) FanOutMessage(origin, label, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FanOutMessage", reflect.TypeOf((*MockSession)(nil).FanOutMessage), origin, label, msg)
}

// GetDCMiddlewares mocks base method.
func (m *MockSession) GetDCMiddlewares() []*sfu.Datachannel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDCMiddlewares")
	ret0, _ := ret[0].([]*sfu.Datachannel)
	return ret0
}

// GetDCMiddlewares indicates an expected call of GetDCMiddlewares.
func (mr *MockSessionMockRecorder) GetDCMiddlewares() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDCMiddlewares", reflect.TypeOf((*MockSession)(nil).GetDCMiddlewares))
}

// GetDataChannels mocks base method.
func (m *MockSession) GetDataChannels(peerID, label string) []*webrtc.DataChannel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataChannels", peerID, label)
	ret0, _ := ret[0].([]*webrtc.DataChannel)
	return ret0
}

// GetDataChannels indicates an expected call of GetDataChannels.
func (mr *MockSessionMockRecorder) GetDataChannels(peerID, label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataChannels", reflect.TypeOf((*MockSession)(nil).GetDataChannels), peerID, label)
}

// GetFanOutDataChannelLabels mocks base method.
func (m *MockSession) GetFanOutDataChannelLabels() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFanOutDataChannelLabels")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetFanOutDataChannelLabels indicates an expected call of GetFanOutDataChannelLabels.
func (mr *MockSessionMockRecorder) GetFanOutDataChannelLabels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFanOutDataChannelLabels", reflect.TypeOf((*MockSession)(nil).GetFanOutDataChannelLabels))
}

// GetPeer mocks base method.
func (m *MockSession) GetPeer(peerID string) sfu.Peer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPeer", peerID)
	ret0, _ := ret[0].(sfu.Peer)
	return ret0
}

// GetPeer indicates an expected call of GetPeer.
func (mr *MockSessionMockRecorder) GetPeer(peerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPeer", reflect.TypeOf((*MockSession)(nil).GetPeer), peerID)
}

// ID mocks base method.
func (m *MockSession) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockSessionMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockSession)(nil).ID))
}

// OnClose mocks base method.
func (m *MockSession) OnClose(f func()) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnClose", f)
}

// OnClose indicates an expected call of OnClose.
func (mr *MockSessionMockRecorder) OnClose(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnClose", reflect.TypeOf((*MockSession)(nil).OnClose), f)
}

// Peers mocks base method.
func (m *MockSession) Peers() []sfu.Peer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Peers")
	ret0, _ := ret[0].([]sfu.Peer)
	return ret0
}

// Peers indicates an expected call of Peers.
func (mr *MockSessionMockRecorder) Peers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Peers", reflect.TypeOf((*MockSession)(nil).Peers))
}

// Publish mocks base method.
func (m *MockSession) Publish(router sfu.Router, r sfu.Receiver) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Publish", router, r)
}

// Publish indicates an expected call of Publish.
func (mr *MockSessionMockRecorder) Publish(router, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockSession)(nil).Publish), router, r)
}

// RelayPeers mocks base method.
func (m *MockSession) RelayPeers() []*sfu.RelayPeer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RelayPeers")
	ret0, _ := ret[0].([]*sfu.RelayPeer)
	return ret0
}

// RelayPeers indicates an expected call of RelayPeers.
func (mr *MockSessionMockRecorder) RelayPeers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RelayPeers", reflect.TypeOf((*MockSession)(nil).RelayPeers))
}

// RemovePeer mocks base method.
func (m *MockSession) RemovePeer(peer sfu.Peer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemovePeer", peer)
}

// RemovePeer indicates an expected call of RemovePeer.
func (mr *MockSessionMockRecorder) RemovePeer(peer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePeer", reflect.TypeOf((*MockSession)(nil).RemovePeer), peer)
}

// Subscribe mocks base method.
func (m *MockSession) Subscribe(peer sfu.Peer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Subscribe", peer)
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockSessionMockRecorder) Subscribe(peer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockSession)(nil).Subscribe), peer)
}
