// Code generated by MockGen. DO NOT EDIT.
// Source: subscriber.go
//
// Generated by this command:
//
//	mockgen -source subscriber.go -destination mock/subscriber.go
//

// Package mock_sfu is a generated GoMock package.
package mock_sfu

import (
	context "context"
	reflect "reflect"

	sfu "github.com/HMasataka/choice/pkg/sfu"
	v4 "github.com/pion/webrtc/v4"
	gomock "go.uber.org/mock/gomock"
)

// MockSubscriber is a mock of Subscriber interface.
type MockSubscriber struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriberMockRecorder
	isgomock struct{}
}

// MockSubscriberMockRecorder is the mock recorder for MockSubscriber.
type MockSubscriberMockRecorder struct {
	mock *MockSubscriber
}

// NewMockSubscriber creates a new mock instance.
func NewMockSubscriber(ctrl *gomock.Controller) *MockSubscriber {
	mock := &MockSubscriber{ctrl: ctrl}
	mock.recorder = &MockSubscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriber) EXPECT() *MockSubscriberMockRecorder {
	return m.recorder
}

// AddDataChannel mocks base method.
func (m *MockSubscriber) AddDataChannel(label string) (*v4.DataChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDataChannel", label)
	ret0, _ := ret[0].(*v4.DataChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddDataChannel indicates an expected call of AddDataChannel.
func (mr *MockSubscriberMockRecorder) AddDataChannel(label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDataChannel", reflect.TypeOf((*MockSubscriber)(nil).AddDataChannel), label)
}

// AddDatachannel mocks base method.
func (m *MockSubscriber) AddDatachannel(ctx context.Context, peer sfu.Peer, dc *sfu.Datachannel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDatachannel", ctx, peer, dc)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDatachannel indicates an expected call of AddDatachannel.
func (mr *MockSubscriberMockRecorder) AddDatachannel(ctx, peer, dc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDatachannel", reflect.TypeOf((*MockSubscriber)(nil).AddDatachannel), ctx, peer, dc)
}

// AddDownTrack mocks base method.
func (m *MockSubscriber) AddDownTrack(streamID string, downTrack sfu.DownTrack) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddDownTrack", streamID, downTrack)
}

// AddDownTrack indicates an expected call of AddDownTrack.
func (mr *MockSubscriberMockRecorder) AddDownTrack(streamID, downTrack any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDownTrack", reflect.TypeOf((*MockSubscriber)(nil).AddDownTrack), streamID, downTrack)
}

// AddICECandidate mocks base method.
func (m *MockSubscriber) AddICECandidate(candidate v4.ICECandidateInit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddICECandidate", candidate)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddICECandidate indicates an expected call of AddICECandidate.
func (mr *MockSubscriberMockRecorder) AddICECandidate(candidate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddICECandidate", reflect.TypeOf((*MockSubscriber)(nil).AddICECandidate), candidate)
}

// Close mocks base method.
func (m *MockSubscriber) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSubscriberMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSubscriber)(nil).Close))
}

// CreateOffer mocks base method.
func (m *MockSubscriber) CreateOffer() (v4.SessionDescription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOffer")
	ret0, _ := ret[0].(v4.SessionDescription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOffer indicates an expected call of CreateOffer.
func (mr *MockSubscriberMockRecorder) CreateOffer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOffer", reflect.TypeOf((*MockSubscriber)(nil).CreateOffer))
}

// DataChannel mocks base method.
func (m *MockSubscriber) DataChannel(label string) *v4.DataChannel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataChannel", label)
	ret0, _ := ret[0].(*v4.DataChannel)
	return ret0
}

// DataChannel indicates an expected call of DataChannel.
func (mr *MockSubscriberMockRecorder) DataChannel(label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataChannel", reflect.TypeOf((*MockSubscriber)(nil).DataChannel), label)
}

// DownTracks mocks base method.
func (m *MockSubscriber) DownTracks() []sfu.DownTrack {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownTracks")
	ret0, _ := ret[0].([]sfu.DownTrack)
	return ret0
}

// DownTracks indicates an expected call of DownTracks.
func (mr *MockSubscriberMockRecorder) DownTracks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownTracks", reflect.TypeOf((*MockSubscriber)(nil).DownTracks))
}

// GetDatachannel mocks base method.
func (m *MockSubscriber) GetDatachannel(label string) *v4.DataChannel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatachannel", label)
	ret0, _ := ret[0].(*v4.DataChannel)
	return ret0
}

// GetDatachannel indicates an expected call of GetDatachannel.
func (mr *MockSubscriberMockRecorder) GetDatachannel(label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatachannel", reflect.TypeOf((*MockSubscriber)(nil).GetDatachannel), label)
}

// GetDownTracks mocks base method.
func (m *MockSubscriber) GetDownTracks(streamID string) []sfu.DownTrack {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDownTracks", streamID)
	ret0, _ := ret[0].([]sfu.DownTrack)
	return ret0
}

// GetDownTracks indicates an expected call of GetDownTracks.
func (mr *MockSubscriberMockRecorder) GetDownTracks(streamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDownTracks", reflect.TypeOf((*MockSubscriber)(nil).GetDownTracks), streamID)
}

// GetMediaEngine mocks base method.
func (m *MockSubscriber) GetMediaEngine() *v4.MediaEngine {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaEngine")
	ret0, _ := ret[0].(*v4.MediaEngine)
	return ret0
}

// GetMediaEngine indicates an expected call of GetMediaEngine.
func (mr *MockSubscriberMockRecorder) GetMediaEngine() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaEngine", reflect.TypeOf((*MockSubscriber)(nil).GetMediaEngine))
}

// GetPeerConnection mocks base method.
func (m *MockSubscriber) GetPeerConnection() *v4.PeerConnection {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPeerConnection")
	ret0, _ := ret[0].(*v4.PeerConnection)
	return ret0
}

// GetPeerConnection indicates an expected call of GetPeerConnection.
func (mr *MockSubscriberMockRecorder) GetPeerConnection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPeerConnection", reflect.TypeOf((*MockSubscriber)(nil).GetPeerConnection))
}

// GetUserID mocks base method.
func (m *MockSubscriber) GetUserID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUserID indicates an expected call of GetUserID.
func (mr *MockSubscriberMockRecorder) GetUserID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserID", reflect.TypeOf((*MockSubscriber)(nil).GetUserID))
}

// IsAutoSubscribe mocks base method.
func (m *MockSubscriber) IsAutoSubscribe() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAutoSubscribe")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAutoSubscribe indicates an expected call of IsAutoSubscribe.
func (mr *MockSubscriberMockRecorder) IsAutoSubscribe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAutoSubscribe", reflect.TypeOf((*MockSubscriber)(nil).IsAutoSubscribe))
}

// Negotiate mocks base method.
func (m *MockSubscriber) Negotiate() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Negotiate")
}

// Negotiate indicates an expected call of Negotiate.
func (mr *MockSubscriberMockRecorder) Negotiate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Negotiate", reflect.TypeOf((*MockSubscriber)(nil).Negotiate))
}

// OnICECandidate mocks base method.
func (m *MockSubscriber) OnICECandidate(f func(*v4.ICECandidate)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnICECandidate", f)
}

// OnICECandidate indicates an expected call of OnICECandidate.
func (mr *MockSubscriberMockRecorder) OnICECandidate(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnICECandidate", reflect.TypeOf((*MockSubscriber)(nil).OnICECandidate), f)
}

// OnNegotiationNeeded mocks base method.
func (m *MockSubscriber) OnNegotiationNeeded(f func()) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnNegotiationNeeded", f)
}

// OnNegotiationNeeded indicates an expected call of OnNegotiationNeeded.
func (mr *MockSubscriberMockRecorder) OnNegotiationNeeded(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnNegotiationNeeded", reflect.TypeOf((*MockSubscriber)(nil).OnNegotiationNeeded), f)
}

// RegisterDatachannel mocks base method.
func (m *MockSubscriber) RegisterDatachannel(label string, dc *v4.DataChannel) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterDatachannel", label, dc)
}

// RegisterDatachannel indicates an expected call of RegisterDatachannel.
func (mr *MockSubscriberMockRecorder) RegisterDatachannel(label, dc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterDatachannel", reflect.TypeOf((*MockSubscriber)(nil).RegisterDatachannel), label, dc)
}

// RemoveDownTrack mocks base method.
func (m *MockSubscriber) RemoveDownTrack(streamID string, downTrack sfu.DownTrack) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveDownTrack", streamID, downTrack)
}

// RemoveDownTrack indicates an expected call of RemoveDownTrack.
func (mr *MockSubscriberMockRecorder) RemoveDownTrack(streamID, downTrack any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDownTrack", reflect.TypeOf((*MockSubscriber)(nil).RemoveDownTrack), streamID, downTrack)
}

// SendStreamDownTracksReports mocks base method.
func (m *MockSubscriber) SendStreamDownTracksReports(streamID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendStreamDownTracksReports", streamID)
}

// SendStreamDownTracksReports indicates an expected call of SendStreamDownTracksReports.
func (mr *MockSubscriberMockRecorder) SendStreamDownTracksReports(streamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendStreamDownTracksReports", reflect.TypeOf((*MockSubscriber)(nil).SendStreamDownTracksReports), streamID)
}

// SetRemoteDescription mocks base method.
func (m *MockSubscriber) SetRemoteDescription(desc v4.SessionDescription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRemoteDescription", desc)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRemoteDescription indicates an expected call of SetRemoteDescription.
func (mr *MockSubscriberMockRecorder) SetRemoteDescription(desc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRemoteDescription", reflect.TypeOf((*MockSubscriber)(nil).SetRemoteDescription), desc)
}
