apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sfu-recordings
  namespace: choice-sfu
  labels:
    app.kubernetes.io/name: choice-sfu
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 50Gi
