// Code generated by MockGen. DO NOT EDIT.
// Source: factory.go
//
// Generated by this command:
//
//	mockgen -source factory.go -destination mock/get_or_new.go
//

// Package mock_buffer is a generated GoMock package.
package mock_buffer

import (
	io "io"
	reflect "reflect"

	packetio "github.com/pion/transport/v3/packetio"
	gomock "go.uber.org/mock/gomock"
)

// MockGetOrNew is a mock of GetOrNew interface.
type MockGetOrNew struct {
	ctrl     *gomock.Controller
	recorder *MockGetOrNewMockRecorder
	isgomock struct{}
}

// MockGetOrNewMockRecorder is the mock recorder for MockGetOrNew.
type MockGetOrNewMockRecorder struct {
	mock *MockGetOrNew
}

// NewMockGetOrNew creates a new mock instance.
func NewMockGetOrNew(ctrl *gomock.Controller) *MockGetOrNew {
	mock := &MockGetOrNew{ctrl: ctrl}
	mock.recorder = &MockGetOrNewMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetOrNew) EXPECT() *MockGetOrNewMockRecorder {
	return m.recorder
}

// GetOrNew mocks base method.
func (m *MockGetOrNew) GetOrNew(packetType packetio.BufferPacketType, ssrc uint32) io.ReadWriteCloser {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrNew", packetType, ssrc)
	ret0, _ := ret[0].(io.ReadWriteCloser)
	return ret0
}

// GetOrNew indicates an expected call of GetOrNew.
func (mr *MockGetOrNewMockRecorder) GetOrNew(packetType, ssrc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrNew", reflect.TypeOf((*MockGetOrNew)(nil).GetOrNew), packetType, ssrc)
}
